language: generic
os: linux
matrix:

  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
script: cmake -DCMAKE_BUILD_TYPE=Release && make VERBOSE=1
